# Generated by Django 3.2 on 2021-04-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pirate_Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montantOr', models.FloatField(default=500.0)),
            ],
        ),
        migrations.CreateModel(
            name='Pirate_Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='H', max_length=1)),
            ],
        ),
    ]
