# Generated by Django 3.2 on 2021-04-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pirate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirate_profil',
            name='inventaire',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Pirate.pirate_inventaire'),
        ),
    ]
