# Generated by Django 3.2.6 on 2022-07-09 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pirate', '0002_pirate_profil_inventaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pirate_Carac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdv', models.FloatField(default=100.0)),
                ('dext', models.FloatField()),
                ('intelligence', models.FloatField()),
                ('force', models.FloatField()),
                ('endurance', models.FloatField()),
                ('esquive', models.FloatField()),
                ('prospection', models.FloatField()),
                ('curiosite', models.FloatField()),
                ('xp', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='pirate_profil',
            name='inventaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pirate.pirate_inventaire'),
        ),
        migrations.CreateModel(
            name='Pirate_Metier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveauMetier', models.IntegerField()),
                ('pirate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pirate.pirate_profil')),
            ],
        ),
        migrations.AddField(
            model_name='pirate_profil',
            name='carac',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Pirate.pirate_carac'),
            preserve_default=False,
        ),
    ]
